# Generated by Django 4.0 on 2022-01-07 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userbase',
            options={'verbose_name': 'Users', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='userbase',
            name='address',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
